//! USDT-style probes for Rust.
//!
//! A probe is a named point in a program that a tracer can attach to while the
//! program runs. With no tracer attached a probe costs one enabled check; its
//! arguments are not computed. `anyprobe` emits each platform's native probe
//! format, so the platform's own tools attach:
//!
//! | Target | Probe format | Tracers |
//! |---|---|---|
//! | Linux (x86-64, AArch64) | SystemTap SDT notes with semaphores | bpftrace, perf |
//! | macOS (x86-64, AArch64) | DTrace USDT, built by the linker | dtrace |
//! | Windows | ETW TraceLogging | WPR, PerfView, logman |
//! | anything else | nothing; checks are `false` | none |
//!
//! [`probe`] probes a function's entry and return:
//!
//! ```
//! # #[derive(Debug)] struct Opts;
//! #[anyprobe::probe(provider = "myapp", debug(opts), ret = native)]
//! fn handle(id: u64, path: &str, opts: &Opts) -> u32 {
//!     // ...
//! #   0
//! }
//! # handle(1, "/", &Opts);
//! ```
//!
//! This defines `myapp:handle__entry(id, path, opts)` and
//! `myapp:handle__return(ret)`. Integers, `bool`, `char`, raw pointers, `&str`
//! and `&[u8]` are passed as they are; other arguments are listed in
//! `debug(..)`, `serde(..)` (JSON) or `skip(..)`. The attribute's
//! documentation lists every option.
//!
//! [`probes!`] defines probes to fire from anywhere in a function. Each one
//! becomes a module with `enabled()` and `fire(...)`:
//!
//! ```
//! anyprobe::probes! {
//!     provider = "myapp";
//!
//!     /// A request started.
//!     pub fn request__start(id: u64, path: &str);
//! }
//!
//! fn handle(id: u64, path: &str) {
//!     if request__start::enabled() {
//!         request__start::fire(id, path);
//!     }
//!     // ...
//! }
//! # handle(1, "/");
//! ```
//!
//! Attaching on each platform, for the example above:
//!
//! ```text
//! sudo bpftrace -p PID -e 'usdt:/path/to/bin:myapp:request__start { printf("%s\n", str(arg1, arg2)); }'
//! sudo dtrace -p PID -n 'myapp$target:::request-start { printf("%s\n", copyinstr(arg1, arg2)); }'
//! ```
//!
//! On Windows, start an ETW session for the provider `myapp` (PerfView
//! `*myapp`, or `logman` with the provider's name-derived GUID).
//!
//! # Features
//!
//! - `serde` (default): `serde(..)` in [`probe`], encoding as JSON.
//! - `autoref`: arguments [`probe`] does not list and cannot pass natively
//!   are encoded as JSON if they implement `serde::Serialize`, otherwise with
//!   `{:?}`, instead of being a compile error. Implies `serde`. In generic
//!   code the choice follows the declared bounds: an argument of type `T`
//!   where `T: Debug` is encoded with `{:?}`, even if the concrete type is
//!   also `Serialize`.

#![cfg_attr(docsrs, feature(doc_cfg))]

pub use anyprobe_macros::{probe, probes};
pub use native::Native;

// Public only so `__private` can re-export it.
#[doc(hidden)]
pub mod encode;
mod native;

#[cfg(all(
    target_os = "linux",
    any(target_arch = "x86_64", target_arch = "aarch64")
))]
#[path = "linux.rs"]
mod backend;

#[cfg(all(
    target_os = "macos",
    any(target_arch = "x86_64", target_arch = "aarch64")
))]
#[path = "macos.rs"]
mod backend;

#[cfg(windows)]
#[path = "windows.rs"]
mod backend;

#[cfg(not(any(
    all(
        any(target_os = "linux", target_os = "macos"),
        any(target_arch = "x86_64", target_arch = "aarch64")
    ),
    windows
)))]
#[path = "noop.rs"]
mod backend;

/// Name of the probe backend compiled for this target: `linux-sdt`,
/// `macos-dtrace`, `windows-etw` or `noop`.
pub const BACKEND: &str = backend::NAME;

// Compiles README.md's examples as doctests, so they cannot drift from the API.
#[cfg(doctest)]
#[doc = include_str!("../../../README.md")]
struct ReadmeDoctests;

/// Support for code generated by [`probes!`] and [`probe`]. Not part of the
/// public API: it changes without notice, and only the macros may use it.
#[doc(hidden)]
pub mod __private {
    pub use crate::__anyprobe_define_probe as define_probe;
    pub use crate::__anyprobe_serde_value as serde_value;
    pub use crate::__anyprobe_unlisted as unlisted;
    pub use crate::encode::{self, Value};

    #[cfg(windows)]
    pub use crate::backend::etw;

    /// Whether the `autoref` and `serde` features are on, for tests that
    /// depend on them.
    pub const AUTOREF: bool = cfg!(feature = "autoref");
    /// See [`AUTOREF`].
    pub const SERDE: bool = cfg!(feature = "serde");

    /// Calls `f`. `#[probe]` runs a function's body through this to capture
    /// its return value. Taking `FnOnce` lets the body move out of, and
    /// return borrows of, the arguments it captured, as the function itself
    /// could.
    #[inline(always)]
    pub fn call_once<R>(f: impl FnOnce() -> R) -> R {
        f()
    }

    /// A new invocation id for an `async fn` under `#[probe]`, passed as the
    /// first argument of its probes so a tracer can pair each entry with its
    /// return when calls interleave. Never 0: an id of 0 on a return or
    /// unwind probe means the entry probe was off when the call started.
    #[cold]
    #[inline(never)]
    #[must_use]
    pub fn next_invocation() -> u64 {
        use core::sync::atomic::{AtomicU64, Ordering};
        static NEXT: AtomicU64 = AtomicU64::new(1);
        NEXT.fetch_add(1, Ordering::Relaxed)
    }

    /// Whether this thread is unwinding from a panic, for `#[probe(unwind)]`.
    /// Called from here so the caller's crate needs no `::std` path.
    #[inline]
    #[must_use]
    pub fn panicking() -> bool {
        std::thread::panicking()
    }

    /// Encoding selection for arguments `#[probe]` does not list, with the
    /// `autoref` feature: `Serialize`, then `Debug`, then a compile error.
    ///
    /// Method resolution tries `&&&Select` first and removes one reference
    /// per step, so the first impl whose bounds hold wins. In generic code
    /// the bounds are the declared ones, not the concrete type's.
    #[cfg(feature = "autoref")]
    pub mod autoref {
        use super::Value;

        /// The value being encoded.
        #[derive(Debug)]
        pub struct Select<'a, T>(pub &'a T);

        /// First choice: JSON.
        pub trait ViaSerde<'a> {
            /// The encoded value.
            fn __anyprobe_value(&self) -> Value<'a>;
        }

        impl<'a, T: serde::Serialize> ViaSerde<'a> for &&Select<'a, T> {
            #[inline(always)]
            fn __anyprobe_value(&self) -> Value<'a> {
                Value::serde(self.0)
            }
        }

        /// Second choice: `{:?}`.
        pub trait ViaDebug<'a> {
            /// The encoded value.
            fn __anyprobe_value(&self) -> Value<'a>;
        }

        impl<'a, T: core::fmt::Debug> ViaDebug<'a> for &Select<'a, T> {
            #[inline(always)]
            fn __anyprobe_value(&self) -> Value<'a> {
                Value::debug(self.0)
            }
        }

        /// Neither applies. The impl always matches, so method resolution
        /// ends here, and the bound on the method, never met, is the
        /// compile error (with `NoEncoding`'s message).
        pub trait ViaNone<'a> {
            /// The value's type.
            type Inner;
            /// Never callable.
            fn __anyprobe_value(&self) -> Value<'a>
            where
                Self::Inner: NoEncoding;
        }

        impl<'a, T> ViaNone<'a> for Select<'a, T> {
            type Inner = T;
            fn __anyprobe_value(&self) -> Value<'a>
            where
                T: NoEncoding,
            {
                Value::U64(0)
            }
        }

        /// Implemented by nothing.
        #[diagnostic::on_unimplemented(
            message = "`{Self}` has no probe encoding",
            label = "implements neither `serde::Serialize` nor `Debug`",
            note = "add the argument to `skip(...)` in `#[probe]`, or implement `Debug` or `serde::Serialize` for its type"
        )]
        pub trait NoEncoding {}
    }
}

/// `serde(arg)` in `#[probe]`: the argument as a JSON [`Value`](encode::Value).
#[cfg(feature = "serde")]
#[doc(hidden)]
#[macro_export]
macro_rules! __anyprobe_serde_value {
    ($name:literal, $value:expr) => {
        $crate::__private::Value::serde($value)
    };
}

/// Without the `serde` feature, `serde(arg)` is a compile error. It lives
/// outside the backends so that it fires on every target.
#[cfg(not(feature = "serde"))]
#[doc(hidden)]
#[macro_export]
macro_rules! __anyprobe_serde_value {
    ($name:literal, $value:expr) => {
        ::core::compile_error!(::core::concat!(
            "`serde(",
            $name,
            ")` needs the \"serde\" feature of anyprobe, which is off"
        ))
    };
}

/// An argument `#[probe]` does not list and cannot encode natively, with
/// the `autoref` feature: picks an encoding from the traits it implements.
#[cfg(feature = "autoref")]
#[doc(hidden)]
#[macro_export]
macro_rules! __anyprobe_unlisted {
    ($name:literal, $value:expr) => {{
        #[allow(unused_imports)]
        use $crate::__private::autoref::{ViaDebug as _, ViaNone as _, ViaSerde as _};
        (&&&$crate::__private::autoref::Select($value)).__anyprobe_value()
    }};
}

/// Without the `autoref` feature an unlisted argument that is not natively
/// encodable is a compile error naming the fixes.
#[cfg(not(feature = "autoref"))]
#[doc(hidden)]
#[macro_export]
macro_rules! __anyprobe_unlisted {
    ($name:literal, $value:expr) => {
        ::core::compile_error!(::core::concat!(
            "argument `",
            $name,
            "` has no native probe encoding; add `serde(",
            $name,
            ")`, `debug(",
            $name,
            ")` or `skip(",
            $name,
            ")` to `#[probe]`, or enable the \"autoref\" feature of anyprobe"
        ))
    };
}
