//! USDT-style probes for Rust.
//!
//! A probe is a named point in a program that a tracer can attach to while the
//! program runs. With no tracer attached a probe costs one enabled check; its
//! arguments are not computed. `anyprobe` emits each platform's native probe
//! format, so the platform's own tools attach:
//!
//! | Target | Probe format | Tracers |
//! |---|---|---|
//! | Linux (x86-64, AArch64) | SystemTap SDT notes with semaphores | bpftrace, perf |
//! | macOS (x86-64, AArch64) | DTrace USDT, built by the linker | dtrace |
//! | Windows | ETW TraceLogging | WPR, PerfView, logman |
//! | anything else | nothing; checks are `false` | none |
//!
//! [`probes!`] defines probes. Each one becomes a module with `enabled()` and
//! `fire(...)`:
//!
//! ```
//! anyprobe::probes! {
//!     provider = "myapp";
//!
//!     /// A request started.
//!     pub fn request__start(id: u64, path: &str);
//! }
//!
//! fn handle(id: u64, path: &str) {
//!     if request__start::enabled() {
//!         request__start::fire(id, path);
//!     }
//!     // ...
//! }
//! # handle(1, "/");
//! ```
//!
//! Attaching on each platform, for the example above:
//!
//! ```text
//! sudo bpftrace -p PID -e 'usdt:/path/to/bin:myapp:request__start { printf("%s\n", str(arg1, arg2)); }'
//! sudo dtrace -p PID -n 'myapp$target:::request-start { printf("%s\n", copyinstr(arg1, arg2)); }'
//! ```
//!
//! On Windows, start an ETW session for the provider `myapp` (PerfView
//! `*myapp`, or `logman` with the provider's name-derived GUID).

#![cfg_attr(docsrs, feature(doc_cfg))]

pub use anyprobe_macros::probes;

#[cfg(all(
    target_os = "linux",
    any(target_arch = "x86_64", target_arch = "aarch64")
))]
#[path = "linux.rs"]
mod backend;

#[cfg(all(
    target_os = "macos",
    any(target_arch = "x86_64", target_arch = "aarch64")
))]
#[path = "macos.rs"]
mod backend;

#[cfg(windows)]
#[path = "windows.rs"]
mod backend;

#[cfg(not(any(
    all(
        any(target_os = "linux", target_os = "macos"),
        any(target_arch = "x86_64", target_arch = "aarch64")
    ),
    windows
)))]
#[path = "noop.rs"]
mod backend;

/// Name of the probe backend compiled for this target: `linux-sdt`,
/// `macos-dtrace`, `windows-etw` or `noop`.
pub const BACKEND: &str = backend::NAME;

// Compiles README.md's examples as doctests, so they cannot drift from the API.
#[cfg(doctest)]
#[doc = include_str!("../../../README.md")]
struct ReadmeDoctests;

/// Support for code generated by [`probes!`]. Not part of the public API: it
/// changes without notice, and only the macros may use it.
#[doc(hidden)]
pub mod __private {
    pub use crate::__anyprobe_define_probe as define_probe;
    pub use crate::__anyprobe_define_provider as define_provider;

    #[cfg(windows)]
    pub use crate::backend::etw;
}
