//! Tracer scripts for the probes in a binary: bpftrace, DTrace (D) and a WPR
//! profile.
//!
//! The bpftrace and D scripts print one line per firing: the probe's full
//! name, then each argument as `name=value`.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::Path;

use anyprobe::registry::{ArgInfo, ArgType};

use crate::report::Group;

const GENERATED: &str = concat!("Generated by cargo-anyprobe ", env!("CARGO_PKG_VERSION"));

/// Why a probe gets no clause, or no arguments, in a script.
fn skipped(group: &Group<'_>) -> Option<&'static str> {
    (group.has_site == Some(false)).then_some("no site: its code is not in the binary")
}

/// The arguments to print: `None` (just the name) when the records disagree.
fn printed_args<'g, 'a>(group: &'g Group<'a>) -> (Option<&'g [ArgInfo<'a>]>, Option<&'static str>) {
    match group.args() {
        Some(args) => (Some(args), None),
        None => (
            None,
            Some("functions define it with different arguments; printing none"),
        ),
    }
}

/// The index of each argument's first value, as `argN`.
fn indices<'g, 'a>(args: &'g [ArgInfo<'a>]) -> impl Iterator<Item = (usize, &'g ArgInfo<'a>)> {
    args.iter().scan(0, |next, arg| {
        let index = *next;
        *next += arg.ty.slots();
        Some((index, arg))
    })
}

/// A bpftrace script. `binary` must be absolute: bpftrace resolves `usdt:`
/// paths itself.
pub fn bpftrace(binary: &Path, groups: &[Group<'_>]) -> String {
    let bin = binary.display();
    let mut out = format!(
        "// {GENERATED} for {bin}\n\
         // Run: sudo bpftrace -p PID THIS_FILE\n\
         // bpftrace reads 64 bytes of a string by default (BPFTRACE_MAX_STRLEN).\n"
    );
    for group in groups {
        let full = group.full_name();
        if let Some(why) = skipped(group) {
            let _ = write!(out, "\n// {full}: {why}\n");
            continue;
        }
        let (args, note) = printed_args(group);
        let mut format = full.clone();
        let mut values = Vec::new();
        for (i, arg) in indices(args.unwrap_or_default()) {
            let (spec, value) = match arg.ty {
                t if t.is_text() => ("%s", format!("str(arg{i}, arg{})", i + 1)),
                ArgType::Bytes => ("%r", format!("buf(arg{i}, arg{})", i + 1)),
                ArgType::Ptr => ("0x%lx", format!("arg{i}")),
                t if t.is_signed() => ("%ld", format!("(int64)arg{i}")),
                _ => ("%lu", format!("arg{i}")),
            };
            let _ = write!(format, " {}={spec}", arg.name);
            values.push(value);
        }
        let values: String = values.iter().map(|v| format!(", {v}")).collect();
        out.push('\n');
        if let Some(note) = note {
            let _ = writeln!(out, "// {full}: {note}");
        }
        let _ = write!(
            out,
            "usdt:{bin}:{}:{}\n{{\n\tprintf(\"{format}\\n\"{values});\n}}\n",
            group.provider, group.name
        );
    }
    out
}

/// A D script for `dtrace -p` or `dtrace -c`.
pub fn dtrace(binary: &Path, groups: &[Group<'_>]) -> String {
    let mut out = format!(
        "/*\n * {GENERATED} for {}\n * Run: sudo dtrace -p PID -s THIS_FILE\n */\n\n\
         #pragma D option quiet\n\
         /* The longest encoded argument, 4095 bytes, and its NUL. */\n\
         #pragma D option strsize=4096\n",
        binary.display()
    );
    for group in groups {
        let full = group.full_name();
        if let Some(why) = skipped(group) {
            let _ = write!(out, "\n/* {full}: {why} */\n");
            continue;
        }
        let (args, note) = printed_args(group);
        let mut format = full.clone();
        let mut values = Vec::new();
        for (i, arg) in indices(args.unwrap_or_default()) {
            let (spec, value) = match arg.ty {
                t if t.is_text() => ("%s", format!("copyinstr(arg{i}, arg{})", i + 1)),
                ArgType::Bytes => ("<%u bytes>", format!("arg{}", i + 1)),
                ArgType::Ptr => ("0x%x", format!("arg{i}")),
                t if t.is_signed() => ("%d", format!("arg{i}")),
                _ => ("%u", format!("arg{i}")),
            };
            let _ = write!(format, " {}={spec}", arg.name);
            values.push(value);
        }
        let values: String = values.iter().map(|v| format!(", {v}")).collect();
        out.push('\n');
        if let Some(note) = note {
            let _ = writeln!(out, "/* {full}: {note} */");
        }
        let _ = write!(
            out,
            "{}$target:::{}\n{{\n\tprintf(\"{format}\\n\"{values});\n}}\n",
            group.provider,
            group.name.replace("__", "-")
        );
    }
    out
}

/// The ETW provider GUID TraceLogging derives from `provider`, as WPR and
/// `logman` take it.
pub fn etw_guid(provider: &str) -> String {
    let guid = tracelogging::Guid::from_name(provider);
    String::from_utf8_lossy(&guid.to_utf8_bytes()).into_owned()
}

/// A WPR profile that records every provider in `groups` at level Verbose,
/// with a file-mode and a memory-mode profile.
pub fn wprp(binary: &Path, groups: &[Group<'_>]) -> String {
    let providers: BTreeSet<&str> = groups.iter().map(|g| g.provider).collect();
    let mut out = format!(
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\
         <!--\n  {GENERATED} for {}\n\
         \x20 Record: wpr -start THIS_FILE -filemode, run the program, then wpr -stop OUT.etl\n",
        xml_text(&binary.display().to_string())
    );
    for provider in &providers {
        let _ = writeln!(out, "  Provider {provider}: {}", etw_guid(provider));
        for group in groups.iter().filter(|g| g.provider == *provider) {
            let _ = writeln!(out, "    {}", group.name);
        }
    }
    out.push_str(
        "-->\n<WindowsPerformanceRecorder Version=\"1.0\" Author=\"cargo-anyprobe\">\n  <Profiles>\n    \
         <EventCollector Id=\"anyprobe_collector\" Name=\"anyprobe\">\n      \
         <BufferSize Value=\"1024\"/>\n      <Buffers Value=\"64\"/>\n    </EventCollector>\n",
    );
    for provider in &providers {
        let _ = writeln!(
            out,
            "    <EventProvider Id=\"anyprobe_{provider}\" Name=\"{}\" Level=\"5\"/>",
            etw_guid(provider)
        );
    }
    for mode in ["File", "Memory"] {
        let _ = write!(
            out,
            "    <Profile Id=\"anyprobe.Verbose.{mode}\" Name=\"anyprobe\" \
             Description=\"anyprobe probes\" LoggingMode=\"{mode}\" DetailLevel=\"Verbose\">\n      \
             <Collectors>\n        <EventCollectorId Value=\"anyprobe_collector\">\n          \
             <EventProviders>\n"
        );
        for provider in &providers {
            let _ = writeln!(
                out,
                "            <EventProviderId Value=\"anyprobe_{provider}\"/>"
            );
        }
        out.push_str(
            "          </EventProviders>\n        </EventCollectorId>\n      </Collectors>\n    </Profile>\n",
        );
    }
    out.push_str("  </Profiles>\n</WindowsPerformanceRecorder>\n");
    out
}

/// `text` safe inside an XML comment: no `--`.
fn xml_text(text: &str) -> String {
    text.replace("--", "- -")
}

#[cfg(test)]
#[path = "script_tests.rs"]
mod script_tests;
